version: 2
jobs:
  build:
    docker:
      - image: golang:1.12-stretch
    working_directory: /go/src/github.com/lawrencegripper/azbrowse
    steps:
      - checkout 
      - setup_remote_docker
      - run: 
          name: Build and Publish
          command: export BUILD_NUMBER=${CIRCLE_BUILD_NUM} && bash -f /go/src/github.com/lawrencegripper/azbrowse/scripts/ci.sh